In [1]:
import numpy as np

In [6]:
arr=np.array([[1,2,3,4],[2,3,4,5]])

In [7]:
arr.ndim

2

In [9]:
arr.shape

(2, 4)

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr1 = np.array(
    [    
        [
            [1,2,3,4,5],
            [2,3,4,5,6],
            [3,7,4,5,6],
            [3,1,4,6,7],
        ],
        [
            [222,2,3,4,5],
            [22,33,44,55,66],
            [33,33,44,55,66],
            [44,21,32,34,55],
        ]
    ]
) 

In [12]:
arr1.shape

(2, 4, 5)

In [13]:
arr1[0][1][1]

3

In [16]:
np.zeros((5), dtype=np.int)

array([0, 0, 0, 0, 0])

In [17]:
np.zeros(b(2,1))

array([[0.],
       [0.]])

In [18]:
np.ones((5,6,2),dtype=np.int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [20]:
np.arange(2,60,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59])

In [23]:
np.linspace(0,60,6)

array([ 0., 12., 24., 36., 48., 60.])

In [25]:
np.logspace(0,10,6)

array([1.e+00, 1.e+02, 1.e+04, 1.e+06, 1.e+08, 1.e+10])

In [29]:
np.arange(2,20,2).reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
np.random.random((2,3,4))

array([[[0.73825268, 0.29572982, 0.03712855, 0.38968365],
        [0.70316788, 0.72193017, 0.70515848, 0.53397618],
        [0.42240239, 0.505737  , 0.27035227, 0.2172391 ]],

       [[0.82192842, 0.47925556, 0.39052208, 0.34029485],
        [0.00238937, 0.79892262, 0.31039975, 0.24766216],
        [0.90328578, 0.00832246, 0.85172747, 0.98493068]]])

In [31]:
np.random.random([2,3,4])

array([[[0.92503212, 0.8028258 , 0.03253327, 0.69787667],
        [0.98378143, 0.68446803, 0.22225671, 0.59087799],
        [0.19618336, 0.19684363, 0.8391216 , 0.93600356]],

       [[0.29347459, 0.4191352 , 0.63620355, 0.42687859],
        [0.68411036, 0.00211809, 0.90425724, 0.34013216],
        [0.91050551, 0.37629708, 0.32054937, 0.32537636]]])

In [33]:
np.random.random_sample((2,3))

array([[0.77953531, 0.10764912, 0.91613489],
       [0.07574749, 0.80744367, 0.12554688]])

In [39]:
arr2 = np.arange(2,20,4)
arr2

array([ 2,  6, 10, 14, 18])

In [40]:
arr2.dtype

dtype('int64')

In [41]:
arr3=arr2.astype('float')

In [42]:
arr3

array([ 2.,  6., 10., 14., 18.])

In [43]:
arr01=np.arange(20)
arr01

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr01.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr01.reshape((2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [47]:
arr01+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [52]:
arr02=np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])
arr03=np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])

In [64]:
print(arr03)
print(arr02)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


In [65]:
arr03.dot(arr02)

array([[ 6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18],
       [24, 24, 24, 24, 24],
       [30, 30, 30, 30, 30]])